### ISSUE TITLE
RuntimeError: numel: integer multiplication overflow

### ISSUE THREAD

**Issue by hyeon9698** [jiaw-z/CoR-GS#28]
![image](https://github.com/user-attachments/assets/6cad0ae8-cc55-4bc3-8c26-c691f34ce445)

I encountered a RuntimeError: numel: integer multiplication overflow when running the LLFF dataset. The error occurs at the following line:
```
GsDict[f"gs{i}"].max_radii2D[visibility_filter] = torch.max(GsDict[f"gs{i}"].max_radii2D[visibility_filter], radii[visibility_filter])
```
error: `RuntimeError: numel: integer multiplication overflow`

It seems to be related to tensor size or an integer overflow during multiplication. I’m not sure why this is happening or how to fix it.
How can I resolve or prevent this overflow?

Thank you

**Comment by jiaw-z** [comment]
Hello, is there still such a problem? I didn't encounter such an error when I ran it. Can you show the shape of each tensor?

**Comment by hyeon9698** [comment]
Hi, I resolved the issue by resetting the environment. Everything is working fine now.
Sorry for any inconvenience, and thanks for your help!
